const mongoose = require('mongoose');

const customerSchema = new mongoose.Schema({
  customerName: { type: String, default: '' },
  name: { type: String, default: '' },
  fatherName: { type: String, default: '' },
  phone: { type: String, default: '' },
  mobileNo: { type: String, default: '' },
  aadhar: { type: String, default: '' },
  pan: { type: String, default: '' },
  address: { type: String, default: '' },
  district: { type: String, default: '' },
  pinCode: { type: String, default: '' },
  dob: { type: String, default: '' },
  vehicleModel: { type: String, default: '' },
  variant: { type: String, default: '' },
  vehicleColor: { type: String, default: '' },
  color: { type: String, default: '' },
  engineNo: { type: String, default: '' },
  chassisNo: { type: String, default: '' },
  registrationNo: { type: String, default: '' },
  keyNo: { type: String, default: '' },
  batteryNo: { type: String, default: '' },
  invoiceDate: { type: String, default: '' },
  financeCompany: { type: String, default: '' },
  financerName: { type: String, default: '' },
  price: { type: Number, default: 0 },
  insurance: { type: Number, default: 0 },
  rto: { type: Number, default: 0 },
  isNew: { type: Boolean, default: false },
  pendingAmount: { type: Number, default: 0 },
  firstServiceDate: { type: String, default: '' },
  secondServiceDate: { type: String, default: '' },
  thirdServiceDate: { type: String, default: '' },
}, { timestamps: true, strict: false });

module.exports = mongoose.model('Customer', customerSchema);